apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-cronjob
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: echo-hello-world
              image: busybox
              args:
                - /bin/sh
                - -c
                - echo "Hello, World"
          restartPolicy: OnFailure
