apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-container
  template:
    metadata:
      labels:
        app: hello-world-container
    spec:
      containers:
        - name: hello-world-container
          image: strm/helloworld-http:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 1
            failureThreshold: 2
